# Generated by Django 5.0.1 on 2024-03-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.CharField(default='', max_length=250),
        ),
    ]
